### ISSUE TITLE
No prioritario - Mejorar el responsive del nuevo texto con imagenes de la home 

### ISSUE THREAD

**Issue by Mirnixx** [gonzalonf/trabajo-integrador#12]
Si alguien tiene tiempo y ganas, de manera no prioritaria.

Mejorar el responsive del texto con imagenes que hay ahora donde estaba el FAQ >>> modificarlo de manera que los iconos queden sobre los textos SOLAMENTE en modo mobile (casi seguro habra que rehacerlo con divs)

**Comment by gonzalonf** [comment]
no estaría entendiendo.. querés que **NO** se vean los íconos en modo laptop?

**Comment by Mirnixx** [comment]
Lo ideal es que SI se vean los iconos en modo mobile, pero quede el icono arriba y el texto abajo. Si sigue sin entenderse, preguntame!

**Comment by gonzalonf** [comment]
ok... entendí....lo hago?
