### ISSUE TITLE
Correcciones a resolver antes de la entrega (agregar las que encuentren)

### ISSUE THREAD

**Issue by gonzalonf** [gonzalonf/trabajo-integrador#13]
- [x]  tal vez lo vea solo yo... pero me parece que hay un pequeño offset hacia abajo del botón de ingreso
centrado: me quedaron un poco hacia la derecha los botones de la portada
- [x] LOGIN scroll: no funciona en modo móvil, donde debería para teléfonos chicos
- [x] LOGIN. Al abrir en mobil.. algunas veces se carga solo el login, sin cliquear INGRESAR
- [ ] Hamburguesa... le falta panceta(?) XD . NO, capaz debería cerrarse cuando elegis opcion, para que no quede tapando
- [x] corregir links en registro 
- [ ] responsive registro (que expanda en modo móbil)

**Comment by Mirnixx** [comment]
1. Hice unos ajustes, lo sigo bien bien. Como lo ven los demas, ahora?
2. Arregle el centrado de los botones (estaba en los pendientes de arriba y lo sacaste).

**Comment by gonzalonf** [comment]
5. Tal vez sea solo con linux. te muestro lo que veo (igual es mínimo)
![offset2](https://cloud.githubusercontent.com/assets/22066985/24869418/947ce0dc-1de9-11e7-92fe-4b088cb565fe.jpeg)
